### ISSUE TITLE
Brussels projection

### ISSUE THREAD

**Issue by tristen** [openaddresses/openaddresses.io#39] opened 2015-01-05 16:20 UTC
I tried visualizing the openaddress data using `sbma44.8dkotj4i` and it looks like the projection is messed up.

![screen shot 2015-01-05 at 11 18 16 am](https://cloud.githubusercontent.com/assets/61150/5615795/ab23a968-94cc-11e4-9ff6-69ee29a0086c.png)

cc @sbma44

**Comment by sbma44** [comment] 2015-01-05 16:22
I think this is the result of getting SRSes mixed up from a template file. Regenerating, will rebuild the mbtiles once I've confirmed the fix. Depending on how speedy unpacker is feeling, the source might be updated by the end of the day.

https://github.com/openaddresses/openaddresses/issues/760
https://github.com/openaddresses/openaddresses/pull/765/files

**Comment by sbma44** [comment] 2015-01-05 17:48
[Looks like the Brussels release has a busted custom SRS](http://lists.osgeo.org/pipermail/qgis-user/2011-December/014895.html) -- this isn't just a question of finding the right EPSG code. Adding support for this to `conform` doesn't seem worth it, so I've fixed the data locally and stuck it up in /cache. PR to follow.

![image](https://cloud.githubusercontent.com/assets/31717/5617100/fa1e4044-94d8-11e4-9eb3-45603a774552.png)

**Comment by sbma44** [comment] 2015-01-05 17:52
merged at https://github.com/openaddresses/openaddresses/pull/818. now rebuilding mbtiles; will close ticket once that's done.

**Comment by sbma44** [comment] 2015-01-06 03:14
OK! after one false start the data source is updated and rendering properly in Studio. Looks like the tiles in the openaddresses.io slippy map are still regenerating, but they should be fine, so I'm going to close this for now. Please reopen if you see any trouble.

**Closed as completed by sbma44** 2015-01-06 03:14 UTC
